Use replace(char,char) instead of replaceAll(regexp,string)
This should fix this crash report:

java.lang.StringIndexOutOfBoundsException: String index out of range: 1
at java.lang.String.charAt(String.java:658)
at java.util.regex.Matcher.appendReplacement(Matcher.java:762)
at java.util.regex.Matcher.replaceAll(Matcher.java:906)
at java.lang.String.replaceAll(String.java:2162)
at com.android.tools.idea.wizard.NewProjectWizard$1.run(NewProjectWizard.java:141)

Change-Id: I38f1e120d9a874bcc14771d732430f2b84ac9a4a