[android] IDEA-357378 replace usages of StudioFlags.GRADLE_DECLARATIVE_IDE_SUPPORT with the registry key
`intellij.android.gradle.dsl.declarative` has been accessing `com/android/tools/idea/flags/StudioFlags` class.
`intellij.android.gradle.dsl.declarative` module is used in the `intellij.gradle` plugin. `intellij.gradle` plugin doesn't bundle the `com/android/tools/idea/flags/StudioFlags` class, which leads to `java.lang.NoClassDefFoundError` runtime errors.

To prevent NCDFE errors, StudioFlags are replaced with RegistryKey `android.gradle.ide.gradle.declarative.ide.support`.

GitOrigin-RevId: 1f51ab48e60317d5daaba8ab14004714c11b3fd2