Now IDE handles incompatible combination of plugin 2.2 (or older) and Gradle 4.4 (or newer.)
Instead of showing a NoSuchMethodError, the IDE will display a user-friendly
error message giving the user the choice to either update the plugin to 2.4
or downgrade Gradle to 3.5

Bug: 37508452

Test: JUnit test
Change-Id: Ib8438c0058f9e4a361d9338efee1d8570938535b