Allow accessing android.jar from the android plugin
When running the GradleFileMergerTest, the following assertion is
being triggered (only with IDEA14, not IDEA13):

  java.lang.AssertionError: File accessed outside allowed roots: \
      file:///path/to/tools/adt/idea/android/testData/android.jar;

The list of allowed roots includes the idea source root, but since
the android plugin sits outside of that, this CL adds the android
plugin home as an explicitly allowed source root.

Change-Id: I15e3cbb3e9d6fc95199e4e5bd3fe38cdc91f064e