Fix vararg nullability
The code starts throwing an NPE when compiled with kotlinc 2.2.0:
java.lang.NullPointerException: getChild(...) must not be null
	at com.android.tools.idea.gradle.project.sync.GradleFileChangeListener.beforeChildAddition(GradleFileChangeListener.kt:80)
	at com.intellij.psi.impl.PsiManagerImpl.notifyPsiTreeChangeListener(PsiManagerImpl.java:386)

This is most likely due to an upstream fix:
https://github.com/jetbrains/kotlin/commit/963f4b39e82ca8b503b35054602a32a7e1dca9c5

Bug: N/A
Test: N/A
Change-Id: Ia5167e87281d99cbaf1a954ce27f792d690a6d70

GitOrigin-RevId: 44fc4bb4ef4ec5c8e0efc8b5149f775cdd58a85b