[android] Fix test AndroidGradleExecutionConsoleManagerTest#testGetConsoleManager
FakeConfigurationFactory.INSTANCE is passed as 'factory' argument to avoid exception:
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'factory' of com/intellij/execution/configurations/LocatableConfigurationBase.<init> must not be null

(cherry picked from commit ce3f8c4f222811ca08cd3d4e86d6a3d3d331d248)

IJ-MR-120061

GitOrigin-RevId: 370ef44cc08e6c545dcf2d288234965e4c23e1f0