Experiment: flush AWT queue in GradleProjectImporterTest
GradleProjectImporterTest has been flaky recently (fails every 3-4
builds), even though it's not even doing a real Gradle sync. The
failure is "AssertionFailedError: expected:<1> but was:<0>" when
assertEquals(1, modules.length), which made me suspect the model
commit hasn't happened yet.

ProjectManagerImpl#openTestProject suggests flushing the AWT queue
after calling openProject(), to give post-init tasks a chance to run.

Change-Id: I5374d8d77eecba7870cdeb54a588c3d4a38ba7fa