Revert "Fixing broken build due to a typo."
Getting at runtime:
org.gradle.tooling.model.UnsupportedMethodException: Method public abstract java.io.File com.android.builder.model.AndroidBundle.getFolder() not found

This reverts commit c857a5c3c5894f8b0efdb2fde41fb4175d9ad4c6.

Change-Id: I0bf1b4fbe9005c3e57d313a0b4df2e0df4e0e27d