Revert "Updating builder-model to a newer version of 2.2.0-alpha1 (CL 2 of 2)."
Getting at runtime:
org.gradle.tooling.model.UnsupportedMethodException: Method public abstract java.io.File com.android.builder.model.AndroidBundle.getFolder() not found

This reverts commit 92586d7de544bc3ecafa20cd5dff58e0c2a65ff4.

Change-Id: I59c1b6f94bcf77ec08eab82d639f881fa08b94a0