Gracefully handle PSI error nodes in the source code
If there are errors in the source code, the PSI Lombok converter
would log exceptions (and return null for the whole tree). This
CL makes it handle this more gracefully, pruning out subtrees
of the AST. A unit test now randomly mutates PSI documents
repeatedly and checks that the conversion is still successful.

This fixes exceptions of the following that were logged during
for example unit test runs:

[ 180723]   WARN - inspections.IntellijLintClient - Failed converting PSI parse tree to Lombok for file /tmp/unitTest_apiCheck1c_415/unitTest0.tmp/src/p1/p2/MyActivity.java
java.lang.RuntimeException: Could not convert file /tmp/unitTest_apiCheck1c_415/unitTest0.tmp/src/p1/p2/MyActivity.java
	at org.jetbrains.android.inspections.lint.LombokPsiConverter.convert(LombokPsiConverter.java:208)
	at org.jetbrains.android.inspections.lint.LombokPsiParser.parse(LombokPsiParser.java:110)
	at org.jetbrains.android.inspections.lint.LombokPsiParser.parseJava(LombokPsiParser.java:74)

Change-Id: I0a239c01acf3b651b5fe9726708816b92851e384
(cherry picked from commit 2effc03128b5ee81c7b1bf179df71b8c5c805e3a)