Fix memory leak with AnimatedComponentSplitter
Observed when closing Studio (latest build)
java.lang.RuntimeException: Memory leak detected:'com.android.tools.idea.uibuilder.mockup.editor.AnimatedComponentSplitter[,0,1,0x-1,invalid,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777217,maximumSize=,minimumSize=,preferredSize=]'of class com.android.tools.idea.uibuilder.mockup.editor.AnimatedComponentSplitter

Caused by: java.lang.Throwable
	at com.intellij.openapi.ui.ThreeComponentsSplitter.<init>(ThreeComponentsSplitter.java:151)
	at com.android.tools.idea.uibuilder.mockup.editor.AnimatedComponentSplitter.<init>(AnimatedComponentSplitter.java:57)
	at com.android.tools.idea.uibuilder.editor.NlEditorPanel.<init>(NlEditorPanel.java:87)
	at com.android.tools.idea.uibuilder.editor.NlEditor.getComponent(NlEditor.java:59)
	at com.android.tools.idea.uibuilder.editor.NlEditor.getComponent(NlEditor.java:37)
...

Change-Id: I14aa6d69bd0575bc08515d87f4130a62255f8747