ml-api-tests: add dependency on opentest4j
Similar to JUnit4, the opentest4j library is no longer bundled in
IntelliJ 2024.3. Tests that use it must include it themselves.
This change fixes the following error in tests:

  java.lang.NoClassDefFoundError: org/opentest4j/AssertionFailedError

Test: PromptBuilderTest (for example)
Change-Id: I33aad4399ecf5bf61ea145811d092956021b4d66

GitOrigin-RevId: d7bb501b44c818323bf7d72dcc93520b33b4bdd5