Fixed the new memory settings flag that breaks StudioFlagsDialog.
StudioFlagsDialog handles only boolean flags currently. The new
integer flag for memory settings caused:

java.lang.IllegalStateException: Unhandled flag type
("memory.settings.memory.settings.ide.xmx.cap"): Flag<Integer>

This CL changed the flag to boolean.

Bug: 129064894
Test: manual
Change-Id: Ic9d705127a4774ca881aaa2f20cde53f7833ec94