Make Android/SwingFocusRule compatible with Java11 (unit tests only)
java.awt.peer.ComponentPeer#requestFocus method has different signature in Java8 and Java11 (difference is in last argument). JDK8 is used for compilation. In order to make the code run on Java11 reflection is used to invoke the method on Java11 (note that compiled code throws NoSuchMethodError on Java11)

GitOrigin-RevId: 10585789e6d90633122580530e9c1ba0835a3c6b