Android: Add missing id for RulesPersistentStateConverterProvider definition.
id is added to resolve following exception:
SEVERE - #c.i.o.p.i.ProjectManagerImpl - supplier.get()!!.deprecatedId must not be null
java.lang.NullPointerException: supplier.get()!!.deprecatedId must not be null

GitOrigin-RevId: bc634d7edf8cdf8612959a95461be1be1da10acc