Remove usage of testFramework.jar
Despite appearances, 'runWriteActionAndWait' is an API from
testFramework.jar, and thus it is excluded from the IDE runtime
classpath in production. In other words, this code throws
NoClassDefFoundError in release builds (but not during tests nor
dev builds due to b/265335760).

Bug: 265335760
Test: tested by Change I706447510
Change-Id: I12a345f0afd44af38e8dfee5db71542352aa139d

GitOrigin-RevId: f95bf45a68734e88b4a2d3bb17af81ffa8eff9ff