IDEA-CR-54485: IDEA-221306: [Android] Designer attributes not working on JRE 11
On Linux/MacOS CustomComboBox#setUI method fails with NoClassDefFoundError: com/sun/../WindowsComboBoxUI because this class does not exist in JRE11 on linux/mac. On Windows this class exists, but check (ui instanceof WindowsComboBoxUI) evaluates false because ui will be of type WinIntelliJComboBoxUI.

Conclusion: ui may not be of type WindowsComboBoxUI

(cherry picked from commit a3590b8ae0ccc8bc3f46996341a75937e3f843d2)

Change-Id: Ia3590b8ae0ccc8bc3f46996341a75937e3f843d2