Fix createRealJarArchive() to create valid archives
Returning the contents of the byte array before closing the
JarOutputStream is a subtle bug, because close() finishes
writing the end of central directory record and we need that in the
byte array as well.

Currently, we have a flurry of stack traces while running unit tests:

[  16260]   WARN - penapi.vfs.impl.jar.JarHandler - java.util.zip.ZipException: error in opening zip file: /tmp/unitTest_moveArchiveFromNestedModuleWithinProject/testMoveArchiveFromNestedModuleWithinProject/parent/sourcemodule/lib/library.jar
java.lang.RuntimeException: java.util.zip.ZipException: error in opening zip file
	at com.intellij.util.io.FileAccessorCache$1.createValue(FileAccessorCache.java:37)
	at com.intellij.util.io.FileAccessorCache$1.createValue(FileAccessorCache.java:30)
	at com.intellij.util.containers.SLRUCache.get(SLRUCache.java:46)
	at com.intellij.util.io.FileAccessorCache.get(FileAccessorCache.java:62)
	at
        com.intellij.openapi.vfs.impl.ZipHandler.getZipFileHandle(ZipHandler.java:109)
...
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)

Change-Id: I3d569c76662e1e0128183a1dc1a74f0f73600ecf