[android] Use compose compiler sources instead of prebuilt jars in compose-ide-plugin module
Sources are more up to date with the latest master than precompiled compiler-hosted jar
and with using sources we avoid errors as following:
```java.lang.NoClassDefFoundError: org/jetbrains/kotlin/ir/declarations/IrDeclarationOrigin$IR_EXTERNAL_DECLARATION_STUB
	at androidx.compose.compiler.plugins.kotlin.lower.DeepCopyIrTreeWithRemappedComposableTypes.visitConstructorCall(ComposableTypeRemapper.kt:124)
	at androidx.compose.compiler.plugins.kotlin.lower.DeepCopyIrTreeWithRemappedComposableTypes.visitConstructorCall(ComposableTypeRemapper.kt:68)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitConstructorCall(IrElementTransformerVoid.kt:218)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitConstructorCall(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.IrConstructorCall.accept(IrConstructorCall.kt:28)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:30)
```

GitOrigin-RevId: e957ca9691655fa713d14a78c69d8b9879ee39c2