Fix NoSuchMethodError crash
A NoSuchMethodError is an Error, not an Exception. This was
showing up in the logs as

NoSuchMethodEr @ InstantRunManager:303 < :283 < AndroidRunConfigurationBase:280 < ExecutorRegistryImpl:254 < :228 < ActionUtil:114 < Utils:188 < :139>

Change-Id: Ie7fd06b5b2b2972f201093c9590a1f09c4bd4d32
(cherry picked from commit fb6b15bf36a59659edf71e9ae45ce91614cc1f5c)