Revert "Fixing broken build due to a typo."
Getting at runtime:
org.gradle.tooling.model.UnsupportedMethodException: Method public abstract java.io.File com.android.builder.model.AndroidBundle.getFolder() not found

This reverts commit 65f75132f239228c62e1539d455610f3490e9aea.

Change-Id: I0bf1b4fbe9005c3e57d313a0b4df2e0df4e0e27d