Layout Preview: Fix NoSuchMethodError
When using tools:listitem on recycler view, NoSuchMethodError occurred
in some cases.

Change-Id: I7815d996da67641d1871b1b2d73104ab3a7bffdc
(cherry picked from commit 6473e8eb44ed60db7e01efa10c28216658e86952)