Extend catch clause to capture all exceptions thrown during project setup.
This is necessary to ensure syncFailed() is always notified, because otherwise
the event lifecycle breaks and this in particular affects indexing state.

Previously, RuntimeException would not capture NoSuchMethodError apparently thrown
by Kotlin infrastructure under certain circumstances. See the bug referenced.

Bug: b/68310891
Test: N/A in this context.
Change-Id: I68bc06a85381a660cd419f192863eb1625b36932