Android: Ensure Idea resolves process-tracker binaries correctly.
This change enforces IDEA to look for production binaries of process tracker agent.
java.nio.file.NoSuchFileException: $PROJECT_ROOT$/bazel-bin/tools/base/process-monitor/process-tracker-agent/native/x86_64/process-tracker

(cherry-picked from commit 58286331fe5b4fe18bf6bfd89884c3553cfd3c43)

Change-Id: I58286331fe5b4fe18bf6bfd89884c3553cfd3c43

GitOrigin-RevId: 814989b9d5802e7b656ddf6df784bdd046199bb6