IDEA-268850 [merge-android-42] tests: fix IAE at HProfReadBufferSlidingWindow
IllegalAccessError: class com.android.tools.idea.diagnostics.hprof.util.HProfReadBufferSlidingWindow (in unnamed module @0x36d842ff) cannot access class jdk.internal.ref.Cleaner (in module java.base) because module java.base does not export jdk.internal.ref to unnamed module @0x36d842ff

GitOrigin-RevId: 6637dc0360e5aede9d526c4117af06a29ee4c9ce